### Swift Bluetooth library
SWIFT_BLUETOOTH_VERSION = 6.0.3
SWIFT_BLUETOOTH_SITE = $(call github,pureswift,bluetooth,$(SWIFT_BLUETOOTH_VERSION))
SWIFT_BLUETOOTH_LICENSE = MIT
SWIFT_BLUETOOTH_LICENSE_FILES = LICENSE
SWIFT_BLUETOOTH_INSTALL_STAGING = YES
SWIFT_BLUETOOTH_INSTALL_TARGET = YES
SWIFT_BLUETOOTH_DEPENDENCIES = swift foundation
SWIFT_BLUETOOTH_LIBRARIES = Bluetooth BluetoothGAP BluetoothGATT BluetoothHCI

$(eval $(swift-package))
