### Swift Socket library
SWIFT_SOCKET_VERSION = 0.2.0
SWIFT_SOCKET_SITE = $(call github,pureswift,socket,$(SWIFT_SOCKET_VERSION))
SWIFT_SOCKET_LICENSE = Apache-2.0
SWIFT_SOCKET_LICENSE_FILES = LICENSE
SWIFT_SOCKET_INSTALL_STAGING = YES
SWIFT_SOCKET_INSTALL_TARGET = YES
SWIFT_SOCKET_DEPENDENCIES = swift foundation swift-system
SWIFT_SOCKET_LIBRARIES = Socket

$(eval $(swift-package))
