### Grand Central Dispatch
LIBDISPATCH_VERSION = swift-5.6-RELEASE
LIBDISPATCH_SITE = $(call github,apple,swift-corelibs-libdispatch,$(LIBDISPATCH_VERSION))
LIBDISPATCH_LICENSE = Apache-2.0
LIBDISPATCH_LICENSE_FILES = LICENSE
LIBDISPATCH_INSTALL_STAGING = YES
LIBDISPATCH_SUPPORTS_IN_SOURCE_BUILD = NO
LIBDISPATCH_SUPPORTS_CMAKE_TOOLCHAIN = NO
LIBDISPATCH_DEPENDENCIES = libbsd

LIBDISPATCH_CONF_OPTS += \
	-DLibRT_LIBRARIES="${STAGING_DIR}/usr/lib/librt.a" \
	-DCMAKE_C_COMPILER=$(SWIFT_NATIVE_PATH)/clang \
	-DCMAKE_CXX_COMPILER=$(SWIFT_NATIVE_PATH)/clang++ \
	-DCMAKE_C_FLAGS="-w -fuse-ld=lld $(SWIFT_EXTRA_FLAGS) -target $(SWIFT_TARGET_NAME) --sysroot=$(STAGING_DIR) -I$(STAGING_DIR)/usr/include -B$(STAGING_DIR)/usr/lib -B$(HOST_DIR)/lib/gcc/$(GNU_TARGET_NAME)/$(call qstrip,$(BR2_GCC_VERSION)) -L$(HOST_DIR)/lib/gcc/$(GNU_TARGET_NAME)/$(call qstrip,$(BR2_GCC_VERSION))" \
	-DCMAKE_C_LINK_FLAGS="-target $(SWIFT_TARGET_NAME) --sysroot=$(STAGING_DIR)" \
	-DCMAKE_CXX_FLAGS="-w -fuse-ld=lld $(SWIFT_EXTRA_FLAGS) -target $(SWIFT_TARGET_NAME) --sysroot=$(STAGING_DIR) -I$(STAGING_DIR)/usr/include -I$(HOST_DIR)/$(GNU_TARGET_NAME)/include/c++/$(call qstrip,$(BR2_GCC_VERSION))/ -I$(HOST_DIR)/$(GNU_TARGET_NAME)/include/c++/$(call qstrip,$(BR2_GCC_VERSION))/$(GNU_TARGET_NAME) -B$(STAGING_DIR)/usr/lib -B$(HOST_DIR)/lib/gcc/$(GNU_TARGET_NAME)/$(call qstrip,$(BR2_GCC_VERSION)) -L$(HOST_DIR)/lib/gcc/$(GNU_TARGET_NAME)/$(call qstrip,$(BR2_GCC_VERSION))" \
	-DCMAKE_CXX_LINK_FLAGS="-target $(SWIFT_TARGET_NAME) --sysroot=$(STAGING_DIR)" \

define LIBDISPATCH_INSTALL_TARGET_CMDS
	(cd $(LIBDISPATCH_BUILDDIR) && \
	cp ./*.so $(TARGET_DIR)/usr/lib/ \
	)
endef

$(eval $(cmake-package))
