### Swift Linux Bluetooth (Swift BlueZ userland) library
SWIFT_BLUETOOTH_LINUX_VERSION = 5.0.4
SWIFT_BLUETOOTH_LINUX_SITE = $(call github,pureswift,bluetoothlinux,$(SWIFT_BLUETOOTH_LINUX_VERSION))
SWIFT_BLUETOOTH_LINUX_LICENSE = MIT
SWIFT_BLUETOOTH_LINUX_LICENSE_FILES = LICENSE
SWIFT_BLUETOOTH_LINUX_INSTALL_STAGING = YES
SWIFT_BLUETOOTH_LINUX_INSTALL_TARGET = YES
SWIFT_BLUETOOTH_LINUX_DEPENDENCIES = swift foundation swift-bluetooth swift-system swift-socket
SWIFT_BLUETOOTH_LINUX_LIBRARIES = BluetoothLinux

$(eval $(swift-package))
