### Swift GATT library
SWIFT_GATT_VERSION = 3.0.2
SWIFT_GATT_SITE = $(call github,pureswift,gatt,$(SWIFT_GATT_VERSION))
SWIFT_GATT_LICENSE = MIT
SWIFT_GATT_LICENSE_FILES = LICENSE
SWIFT_GATT_INSTALL_STAGING = YES
SWIFT_GATT_INSTALL_TARGET = YES
SWIFT_GATT_DEPENDENCIES = swift foundation swift-bluetooth
SWIFT_GATT_LIBRARIES = GATT

$(eval $(swift-package))
