### Swift WLAN library
SWIFT_WLAN_VERSION = 0.4.0
SWIFT_WLAN_SITE = $(call github,pureswift,wlan,$(SWIFT_WLAN_VERSION))
SWIFT_WLAN_LICENSE = MIT
SWIFT_WLAN_LICENSE_FILES = LICENSE
SWIFT_WLAN_INSTALL_STAGING = YES
SWIFT_WLAN_INSTALL_TARGET = YES
SWIFT_WLAN_DEPENDENCIES = swift foundation
SWIFT_WLAN_EXECUTABLES = wirelesstool

$(eval $(swift-package))
