### Apple's Swift Programming Language
SWIFT_VERSION = 5.4.2
SWIFT_SOURCE = swift-$(SWIFT_VERSION)-RELEASE.tar.gz
SWIFT_SITE = https://github.com/apple/swift/archive/refs/tags
SWIFT_INSTALL_STAGING = YES
SWIFT_INSTALL_TARGET = YES
SWIFT_SUPPORTS_IN_SOURCE_BUILD = NO
SWIFT_DEPENDENCIES = llvm icu
SWIFT_TARGET_ARCH = $(BR2_PACKAGE_SWIFT_TARGET_ARCH)
SWIFT_NATIVE_PATH = /home/coleman/Downloads/swift-5.4.2-RELEASE-ubuntu20.04
ifeq ($(BR2_TOOLCHAIN_HAS_LIBATOMIC),y)
SWIFT_CONF_ENV += LIBS="-latomic"
endif
SWIFT_CONF_ENV += TARGET_CC="$(SWIFT_NATIVE_PATH)/usr/bin/clang"
SWIFT_CONF_ENV += TARGET_CXX="$(SWIFT_NATIVE_PATH)/usr/bin/clang++"
SWIFT_CONF_ENV += HOST_CC="$(SWIFT_NATIVE_PATH)/usr/bin/clang"
SWIFT_CONF_ENV += HOST_CXX="$(SWIFT_NATIVE_PATH)/usr/bin/clang++"

SWIFT_CONF_OPTS +=  \
    -DLLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN=ON \
    -DSWIFT_USE_LINKER=lld \
    -DLLVM_USE_LINKER=lld \
    -DCMAKE_C_COMPILER=$(SWIFT_NATIVE_PATH)/usr/bin/clang \
    -DCMAKE_CXX_COMPILER=$(SWIFT_NATIVE_PATH)/usr/bin/clang++ \
    -DLLVM_DIR=${HOST_DIR}/lib/cmake/llvm \
    -DLLVM_BUILD_LIBRARY_DIR=${HOST_DIR}/lib \
    -DSWIFT_BUILD_RUNTIME_WITH_HOST_COMPILER=ON \
    -DSWIFT_NATIVE_CLANG_TOOLS_PATH=$(SWIFT_NATIVE_PATH)/usr/bin \
    -DSWIFT_NATIVE_SWIFT_TOOLS_PATH=$(SWIFT_NATIVE_PATH)/usr/bin \
    -DSWIFT_BUILD_AST_ANALYZER=OFF \
    -DSWIFT_BUILD_DYNAMIC_SDK_OVERLAY=ON \
    -DSWIFT_BUILD_DYNAMIC_STDLIB=ON \
    -DSWIFT_BUILD_REMOTE_MIRROR=OFF \
    -DSWIFT_BUILD_SOURCEKIT=OFF \
    -DSWIFT_BUILD_STDLIB_EXTRA_TOOLCHAIN_CONTENT=OFF \
    -DSWIFT_BUILD_SYNTAXPARSERLIB=OFF \
    -DSWIFT_BUILD_REMOTE_MIRROR=OFF \
    -DSWIFT_ENABLE_SOURCEKIT_TESTS=OFF \
    -DSWIFT_INCLUDE_DOCS=OFF \
    -DSWIFT_INCLUDE_TOOLS=OFF \
    -DSWIFT_INCLUDE_TESTS=OFF \
    -DSWIFT_HOST_VARIANT_ARCH=$(SWIFT_TARGET_ARCH) \
    -DSWIFT_SDKS=LINUX \
    -DSWIFT_SDK_LINUX_ARCH_$(SWIFT_TARGET_ARCH)_PATH=${STAGING_DIR}  \
    -DSWIFT_SDK_LINUX_ARCH_$(SWIFT_TARGET_ARCH)_LIBC_INCLUDE_DIRECTORY=${STAGING_DIR}/usr/include  \
    -DSWIFT_SDK_LINUX_ARCH_$(SWIFT_TARGET_ARCH)_LIBC_ARCHITECTURE_INCLUDE_DIRECTORY=${STAGING_DIR}/usr/include \
    -DSWIFT_LINUX_$(SWIFT_TARGET_ARCH)_ICU_I18N=${STAGING_DIR}/usr/lib/libicui18n.so \
    -DSWIFT_LINUX_$(SWIFT_TARGET_ARCH)_ICU_UC=${STAGING_DIR}/usr/lib/libicuuc.so \
    -DICU_I18N_LIBRARIES=${STAGING_DIR}/usr/lib/libicui18n.so \
    -DICU_UC_LIBRARIES=${STAGING_DIR}/usr/lib/libicuuc.so \

$(eval $(cmake-package))
