### Swift Netlink library
SWIFT_NETLINK_VERSION = 1.2.0
SWIFT_NETLINK_SITE = $(call github,pureswift,netlink,$(SWIFT_NETLINK_VERSION))
SWIFT_NETLINK_LICENSE = MIT
SWIFT_NETLINK_LICENSE_FILES = LICENSE
SWIFT_NETLINK_INSTALL_STAGING = YES
SWIFT_NETLINK_INSTALL_TARGET = YES
SWIFT_NETLINK_DEPENDENCIES = swift foundation swift-socket
SWIFT_NETLINK_LIBRARIES = Netlink NetlinkGeneric Netlink80211

$(eval $(swift-package))
