### Swift System library
SWIFT_SYSTEM_VERSION = 1.1.1
SWIFT_SYSTEM_SITE = $(call github,apple,swift-system,$(SWIFT_SYSTEM_VERSION))
SWIFT_SYSTEM_LICENSE = Apache-2.0
SWIFT_SYSTEM_LICENSE_FILES = LICENSE.txt
SWIFT_SYSTEM_INSTALL_STAGING = YES
SWIFT_SYSTEM_INSTALL_TARGET = YES
SWIFT_SYSTEM_DEPENDENCIES = swift
SWIFT_SYSTEM_LIBRARIES = SystemPackage

$(eval $(swift-package))
